#
#Team:15
#Yuqi Cao 1186642
#Yaxuan Huang 1118801
#Meng Yang 1193990
#Gangdan Shu 1239032
#Zheng Xu 1291694
#
---
- name: Copy build script
  become: yes
  copy:
    src: build.sh
    dest: /tmp/build.sh   # TODO
    mode: '0644'

- name: Debug
  debug: 
    msg: "{{ groups['COMP90024'] }}"


- name: Build couchdb cluster with docker
  become: yes
  shell: "bash /tmp/build.sh {{ groups['COMP90024'] }} --ip-addr {{ ansible_eth0.ipv4.address }}"
