#
#Team:15
#Yuqi Cao 1186642
#Yaxuan Huang 1118801
#Meng Yang 1193990
#Gangdan Shu 1239032
#Zheng Xu 1291694
#
---
- name: Copy searching script
  become: yes
  copy:
    src: Search.py
    dest: /tmp/Search.py
    mode: '0644'

- name: Copy scratching script
  become: yes
  copy:
    src: Stream.py
    dest: /tmp/Stream.py
    mode: '0644'

- name: Scratching
  become: yes
  shell: "nohup python3 /tmp/Stream.py {{ groups['COMP90024'][0] }} >> /tmp/stream_log.txt &"

- name: Searching
  become: yes
  shell: "nohup python3 /tmp/Search.py {{ groups['COMP90024'][0] }} >> /tmp/search_log.txt &"
